version: '3.1'

services:
  web:
    volumes:
      - /src:/var/www/html
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_NAME: joomla

  joomladb:
    image: mysql:5.7
    volumes:
      - /data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_USER: joomla
      MYSQL_DATABASE: joomla
      MYSQL_PASSWORD: joomla
