version: '3'
services:
  app:
    image: calidad-php
    ports:
      - "3000:80"
    volumes:
      - C:/Users/andra/Desktop/calidad/src:/var/www/html
    networks:
      - my_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my_network

networks:
  my_network:
